### ISSUE TITLE
Using your "CI" for Ubuntu in Qemu?

### ISSUE THREAD

**Issue by a-t-0** [pagekeysolutions/pkos#3]
Dear Stephen, thank you for your work on this, and for creating such a detailed video explaining how to use Qemu in combination with pytest.

## Context
I typically start qemu on a (pre-installed) ubuntu image (with copy-paste enabled) with:
```sh
qemu-system-x86_64 --enable-kvm -m 4096 -machine smm=off -boot order=d \
  ubuntu22_server.img -smp 4 \
  -chardev qemu-vdagent,id=ch1,name=vdagent,clipboard=on \
  -device virtio-serial-pci \
  -device virtserialport,chardev=ch1,id=ch1,name=com.redhat.spice.0
```
and would like to use your code to run a basic test on some code that I run in qemu. 

## Question
Would you happen to know how would I modify your [qemu_driver.py](https://github.com/pagekeytech/pkos/blob/master/test/integration/qemu_driver.py) to load the ubuntu Iso, instead of the pkos?
and would it then (stil) be possible to send keys and read out data similar to how you use it for PageKey Operating System?

Once again, thank you for sharing your work!

**Comment by stephengrice** [comment]
Hey, thanks for writing this up! Did you ever figure this out? Sorry I took so long to get back to you. I have a feeling qemu_driver.py will not adapt well to Ubuntu just because that OS is so much more complicated than PKOS. The integration test is also very fragile, since it's just probing memory to check which characters are displayed onscreen. It is also assuming that you're using VGA text mode to display things on the screen. This **may** be the case for Ubuntu Server, but that technique would definitely not work well if you have any kind of graphics running. I guess it all depends on what exactly you're trying to test - I hope you're able to modify the script to meet your needs!

**Comment by a-t-0** [comment]
Thank you for your clear response, I did not yet get to giving it a try, and was unaware of the differences you mentioned regarding where the data is retrieved from.  Based on that information, I expect another solution/approach may be more appropriate.
